package com.johnfelen.dupsimplified.model.storage.entity.enumerator.workout

enum class LiftNames {
    DEADLIFT,
    HIGH_HANDLE_TRAP_HD_DEADLIFT,
    TRAP_HD_STIFF_LEG_DEADLIFT,
    HIGH_HANDLE_TRAP_HD_ROMANIAN_DEADLIFT,
    UNILATERAL_GLIDING_HAMSTRING_CURL,

    PENDLAY_ROW,
    HIGH_HANDLE_TRAP_HD_ROW,
    TRAP_HD_SEAL_ROW,
    CABLE_SEATED_ROW,
    RING_INVERTED_ROW,

    BENCH_PRESS,
    KADILLAC_SLINGSHOT_REVERSE_GRIP_BENCH_PRESS,
    FLOOR_PRESS,
    KADILLAC_CLOSE_GRIP_BENCH_PRESS,
    RING_PUSH_UP,

    LOW_BAR_SQUAT,
    STAND_STRONG_SQUAT,
    BOX_SQUAT,
    TRAP_HD_ZERCHER_SQUAT,
    DEFICIT_BULGARIAN_SPLIT_SQUAT,

    UPRIGHT_ROW,
    HIGH_HANDLE_TRAP_HD_HIGH_PULL,
    KNEELING_LAT_PULLDOWN,
    STRAIGHT_ARM_PULLDOWN,
    RING_CHIN_UP,

    PRESS,
    PUSH_PRESS,
    Z_PRESS,
    KADILLAC_PRESS,
    RING_DIPS
}